spring:
  application:
    name: cosmo-webapp
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/cosmo?autoReconnect=true
    username: root
    password: 77vismycaR@
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_second_level_cache: false
      hibernate.show_sql: true
      hibernate.hbm2ddl.auto: update
      hibernate.id.new_generator_mappings: false
